
CREATE DATABASE ECOMM;

CREATE TABLE USERS
(

  USER_ID BIGINT PRIMARY KEY,
  USER_FULLNAME VARCHAR(50) NOT NULL,
  USER_EMAIL VARCHAR(255) NOT NULL,
  USER_USERNAME VARCHAR(10) NOT NULL,
  USER_PASSWORD VARCHAR(255) NOT NULL,

);


CREATE TABLE PRODUCTS
(

  PRO_ID BIGINT PRIMARY KEY,
  PRO_NAME VARCHAR(255) NOT NULL,
  PRO_QUANTITY INT NOT NULL,
  PRO_VENDERID BIGINT NOT NULL,


);