
-- DROP DATABASE ECOMM;

CREATE DATABASE ECOMM;

CREATE TABLE USERS
(
  USER_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  USER_FULLNAME VARCHAR(50) NOT NULL,
  USER_EMAIL VARCHAR(255) NOT NULL,
  USER_USERNAME VARCHAR(10) NOT NULL,
  USER_PASSWORD VARCHAR(255) NOT NULL,
  USER_ROLE VARCHAR(10) NOT NULL DEFAULT 'Customer',
  USER_BALANCE BIGINT NOT NULL DEFAULT 100,
  USER_ADDRESS VARCHAR(512) NOT NULL
);


CREATE TABLE PRODUCTS
(
  PRO_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PRO_VENDORID BIGINT NOT NULL,
  PRO_NAME VARCHAR(255) NOT NULL,
  PRO_PRICE FLOAT NOT NULL,
  PRO_QUANTITY INT NOT NULL,
  FOREIGN KEY (PRO_VENDORID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE CART
(
  CART_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PRO_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  CART_ITEMNAME VARCHAR(255) NOT NULL,
  CART_ITEMQUANTITY INT NOT NULL,
  CART_ITEMPRICE FLOAT NOT NULL,
  FOREIGN KEY (CART_USERID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE ORDERS
(
  ORDER_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  PRO_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  ORDER_QUANTITY INT NOT NULL,
  ORDER_STATUS VARCHAR(10) NOT NULL,
  FOREIGN KEY (CART_USERID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

INSERT INTO USERS
  (USER_FULLNAME, USER_EMAIL, USER_USERNAME, USER_PASSWORD, USER_ADDRESS)
VALUES
  ('Yeshwanth G', 'yashu@gmail.com', 'Yashu', '1234', 'abs'),
  ('Prasanna', 'prasanna@gmail.com', 'prasanna', '1234', 'abc');

INSERT INTO USERS
  (USER_FULLNAME, USER_EMAIL, USER_USERNAME, USER_PASSWORD, USER_ROLE, USER_ADDRESS)
VALUES
  ('Akshay N A', 'akshay@gmail.com', 'akshay', '1234', 'Vendor', 'abc');

INSERT INTO PRODUCTS
  (PRO_VENDORID, PRO_NAME, PRO_PRICE, PRO_QUANTITY)
VALUES
  (3, 'Oneplus 5', 32999, 100),
  (3, 'Asus Laptop', 49999, 50),
  (3, 'Sony Headphones', 4999, 200),
  (3, 'Apple Watch Series 6', 39999, 20),
  (3, 'iPhone 12', 69999, 200),
  (3, 'Oneplus Y-series TV 32"', 13999, 100),
  (3, 'Gaming PC with RTX 3090', 105999, 10);


